export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_KITTEN_PENDING = 'REQUEST_KITTEN_PENDING';
export const REQUEST_KITTEN_SUCCESS = 'REQUEST_KITTEN_SUCCESS';
export const REQUEST_KITTEN_FAIL = 'REQUEST_KITTEN_FAIL';